### ISSUE TITLE
remove calendar?

### ISSUE THREAD

**Issue by frankbraun** [cypherpunkguild/cypherpunkguild.org#1]

**Comment by frankbraun** [comment]
I don't see how it makes sense to have a calendar of that form. Maybe just actual links to upcoming events (community call, events we sponsor, etc.).

**Comment by simplulo** [comment]
Events should be in list/table format, not calendar widget: Date, Location, Title, link.
This is probably the most dynamic part of the site, so it should be easily updatable.

**Comment by simplulo** [comment]
Current events to include:
21-27.06, New Hampshire, Porcupine Freedom Festival, https://porcfest.com
1-3.10, Prague, HCPP21, https://twitter.com/Paralelni_polis/status/1392555464857169922?s=20

**Comment by frankbraun** [comment]
Looks good now.
