### ISSUE TITLE
Make Website mobile friendly

### ISSUE THREAD

**Issue by yu1ian** [cypherpunkguild/cypherpunkguild.org#15]
![IMG_7185](https://user-images.githubusercontent.com/61524281/123104150-b36aa300-d404-11eb-8a6a-fe99d810d537.PNG)

On a mobile this happens when I scroll right. Anyway to make it work so nobody can scroll right on a mobile and the text is always in the middle of a screen?

**Comment by frankbraun** [comment]
Looks like @andreybo fixed it in #14, I do not experience it anymore on mobile.
