### ISSUE TITLE
fix links

### ISSUE THREAD

**Issue by frankbraun** [cypherpunkguild/cypherpunkguild.org#3]

**Comment by frankbraun** [comment]
All links (internal & external) should work and we should remove services we don't have (e.g., Mastodon).

**Comment by simplulo** [comment]
We need to discuss Twitter vs. Mastodon. The CPG currently looks a bit hypocritical railing against Big Tech while using Twitter. We should take the easy step of supporting Mastodon. I can create the account in a few minutes.

**Comment by simplulo** [comment]
I created a Mastodon account on the libertarian Liberdon server:
https://liberdon.com/@CypherpunkGuild
Full handle is @CypherpunkGuild@liberdon.com

**Comment by frankbraun** [comment]
"Cypherpunk Guild community" should be a link to the subforum on gov.near.org

**Comment by frankbraun** [comment]
The domain addresses for the funded projects should be clickable.

**Comment by frankbraun** [comment]
https://gov.near.org/tag/cypherpunk-guild
https://cypherpunkguild.medium.com/

**Comment by frankbraun** [comment]
https://www.activism.net/cypherpunk/manifesto.html

**Comment by simplulo** [comment]
Why are non-links in a blue font, as if they were links?

**Comment by frankbraun** [comment]
All links seem to be fixed now. Otherwise please open another issue.
