### ISSUE TITLE
add Twitter links for council members?

### ISSUE THREAD

**Issue by frankbraun** [cypherpunkguild/cypherpunkguild.org#4]

**Comment by simplulo** [comment]
- Arto Bendiken: https://twitter.com/bendiken
- Dani Osorio: https://twitter.com/WaverlyMaven
- Evgeny Kuzyakov: https://twitter.com/ekuzyakov
- Frank Braun: https://twitter.com/thefrankbraun
- Jon Matonis: https://twitter.com/jonmatonis
- Yulian Lavysh: https://twitter.com/yulianNEAR
- Ozymandius: https://twitter.com/4NTSGuild [pending confirmation]
