### ISSUE TITLE
fix YouTube link

### ISSUE THREAD

**Issue by frankbraun** [cypherpunkguild/cypherpunkguild.org#6]

**Comment by simplulo** [comment]
The documentary is broken into four short videos. 
First part:
https://www.youtube.com/watch?v=YWh6Yzr12iQ
Playlist:
https://www.youtube.com/playlist?list=PLBuns9Evn1w-T2RwqMhUnTZbTTe-M-g42
Article with first part embedded, and links to remaining parts:
https://reason.com/video/2020/10/07/before-the-web-the-1980s-dream-of-a-free-and-borderless-virtual-world/

I suggest linking to the Reason article in the text, and to the YouTube video via the image.

**Comment by simplulo** [comment]
The current YouTube link is something bizarre and unrelated.

**Comment by frankbraun** [comment]
It's been fixed by @andreybo in #14.
