### ISSUE TITLE
Press Kit page

### ISSUE THREAD

**Issue by simplulo** [cypherpunkguild/cypherpunkguild.org#9]
At this stage do we need a separate Press Kit page, or would it end up largely being a copy of the main page? I think we will need it, but not yet. 

Here is a standard outline:
	1.	Press contact
	2.	Company data
	3.	Company story
	4.	Media coverage
	5.	Downloadable images (logos, fodder for featured images)
	6.	Press releases and blog posts

**Comment by yu1ian** [comment]
[CPG_Brand_Assets (2).zip](https://github.com/cypherpunkguild/cypherpunkguild.org/files/6698114/CPG_Brand_Assets.2.zip)
![cpg_twitter_header (1)](https://user-images.githubusercontent.com/61524281/123017097-e9267200-d399-11eb-9a22-df83b9a9b55c.png)

**Comment by frankbraun** [comment]
I added the CPG brand assets, that's good enough for now.
